name: 每小时检查并同步更新仓库

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT1 }}
      - name: 检查仓库更新
        run: |
          git remote add upstream https://github.com/ultralytics/yolov5
          git config --global user.name "sungamma"
          git config --global user.email  "33790+sungamma@users.noreply.github.com"
          git fetch --dry-run upstream
          if [ $? -eq 0 ]; then
            git fetch upstream
            git rebase upstream/master
            git push origin master -f
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
